extends TestCase
## Mixamo pipeline: clips in Mixamo's format (fixtures generated by
## art/blender/make_mixamo_fixtures.py), retargeted at import by
## tools/setup_mixamo.gd, playing on the real default VRM character.

const FIXTURES := "res://tests/fixtures/mixamo"

var model: CharacterModel


func before_each() -> void:
	model = CharacterModel.new()
	model.model_path = CharacterModel.DEFAULT_MODEL
	model.clip_dir = FIXTURES
	root.add_child(model)


func _bone(bone: StringName) -> Vector3:
	var skel := model.skeleton
	return model.to_local(skel.global_transform * skel.get_bone_global_pose(skel.find_bone(bone)).origin)


func _posed() -> void:
	await model.skeleton.skeleton_updated


func test_bone_map_covers_mixamo_skeleton() -> void:
	var map: BoneMap = load("res://assets/animations/mixamo_bone_map.tres")
	assert_true(map.profile is SkeletonProfileHumanoid)
	assert_eq(map.get_skeleton_bone_name(&"LeftUpperArm"), &"mixamorig_LeftArm")
	assert_eq(map.get_skeleton_bone_name(&"Chest"), &"mixamorig_Spine1")
	assert_eq(map.get_skeleton_bone_name(&"RightToes"), &"mixamorig_RightToeBase")


func test_fixture_clips_are_retargeted_and_loaded() -> void:
	var lib := CharacterAnimator.load_library(FIXTURES)
	assert_true(lib.has_animation(&"idle") and lib.has_animation(&"run"), "both clips loaded")
	var run := lib.get_animation(&"run")
	assert_true(String(run.track_get_path(0)).begins_with("%GeneralSkeleton:"), "humanoid track paths")
	assert_eq(run.loop_mode, Animation.LOOP_LINEAR)


func test_clips_take_over_locomotion() -> void:
	var anim := model.animator
	assert_true(anim.clips != null, "clip player created")
	assert_true(model.poser.clip_states.has(HumanoidPoser.Pose.LOCOMOTION))
	assert_false(model.poser.clip_states.has(HumanoidPoser.Pose.GUARD), "no guard clip -> procedural guard")
	anim.speed_ratio = 1.0
	await root.get_tree().process_frame
	await root.get_tree().process_frame
	assert_eq(anim.clips.current_animation, &"run")
	anim.speed_ratio = 0.0
	await root.get_tree().process_frame
	assert_eq(anim.clips.current_animation, &"idle")


func test_run_clip_moves_the_vrm_legs() -> void:
	model.animator.speed_ratio = 1.0
	var min_z := INF
	var max_z := -INF
	var hips_y := 0.0
	for i in 60:
		await _posed()
		var z := _bone(&"LeftFoot").z - _bone(&"RightFoot").z
		min_z = minf(min_z, z)
		max_z = maxf(max_z, z)
		hips_y = _bone(&"Hips").y
		# Retargeting must not flip or twist the legs above the hips.
		assert_true(_bone(&"LeftFoot").y < hips_y, "foot stays below hips")
	assert_true(max_z - min_z > 0.1, "feet swing past each other (%.2f)" % (max_z - min_z))


func test_hand_seals_layer_over_clips() -> void:
	model.animator.pose = HumanoidPoser.Pose.WEAVE
	for i in 40:
		await root.get_tree().process_frame
	await _posed()
	var arm := _bone(&"LeftUpperArm").distance_to(_bone(&"LeftLowerArm")) \
		+ _bone(&"LeftLowerArm").distance_to(_bone(&"LeftHand"))
	assert_true(_bone(&"LeftHand").distance_to(_bone(&"RightHand")) < 0.2 * arm, "palms together over idle clip")
	assert_eq(model.animator.clips.current_animation, &"idle", "legs still from the clip")
